---
- hosts: workstation

  tasks:
    - name: install github
      mac_pkg: pkg_type=app
               url=https://central.github.com/mac/latest
               archive_type=zip archive_path='GitHub Desktop.app'
      sudo: yes

